### ISSUE TITLE
Log tags are not detailed to analyze

### ISSUE THREAD

**Issue by siaeyy** [sirius-tedarik/sirutils#23]
All logs of wizard services have same tag, and this shouldn't be like this because in this way logs are not easy to analyze. For each service, there should a tag. I think the solution is creating a logger instance with service's own tag and overwriting it to service's logger that inherited from broker.

**Comment by siaeyy** [comment]
Would you please create a new branch for this feature's development?
@giveerr

**Comment by giveerr** [comment]
completed
