### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by siaeyy** [sirius-tedarik/sirutils#25]
Wizard needs swagger support,
it should create automaticly swagger datas and publish these.

**Comment by siaeyy** [comment]
The support implementation is tried [here](https://github.com/siaeyy/sirutils/tree/swagger)

**Comment by giveerr** [comment]
We're planning to move to our own microservice library instead of moleculer so wizard *is not* open to any new feature until then.

Thanks for your great work
